export {default as Blog} from './blog/Blog'
export {default as Features } from './feature/Features'
export {default as Footer } from './footer/Footer'
export {default as Header } from './header/Header'
export {default as Possiblity} from './possiblitiy/Possible'
export {default as WhatGPT3} from './whatGpt3/What'